WIFI_SSID = "NOVAPixelProHOTSPOT"
WIFI_PASSWORD = "YOUR WIFI PASSWORD"

#WIFI_SSID = "YOUR WIFI NAME/SSID"
#WIFI_PASSWORD = "YOUR WIFI PASSWORD"

botToken = "940494553:AAG0niJWje6Hs63Ta-evnytSzwyWcYxCw-c"
